# Generated by Django 3.2.5 on 2022-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('Place', models.CharField(max_length=1000)),
                ('googlelink', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
