# Generated by Django 3.2.5 on 2022-06-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Event',
            old_name='Place',
            new_name='place',
        ),
    ]
