# Generated by Django 3.2.5 on 2022-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='drive',
            field=models.BooleanField(default=False, help_text='Check if this is a drive'),
        ),
        migrations.AddField(
            model_name='event',
            name='hotel',
            field=models.BooleanField(default=False, help_text='Check if this is a hotel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='googlelink',
            field=models.CharField(blank=True, help_text='Link to TripAdvisor or the Hotel (Optional)', max_length=1000),
        ),
    ]
