# Generated by Django 3.2.5 on 2022-06-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=500),
        ),
    ]
