# Generated by Django 3.2.5 on 2022-06-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20220618_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, editable=False, help_text='Description of the event (Optional)', max_length=600),
        ),
    ]
